//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Necrui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalSettingsDescRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalSettingsDescRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Necrui.GlobalSettingsDescRes", typeof(GlobalSettingsDescRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to set the number of Pokemon from your collection to display when starting the bot, set to 0 for none..
        /// </summary>
        internal static string AmountOfPokemonToDisplayOnStart {
            get {
                return ResourceManager.GetString("AmountOfPokemonToDisplayOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string AmountOfTimesToUpgradeLoop {
            get {
                return ResourceManager.GetString("AmountOfTimesToUpgradeLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google and Pokemon Trainer&apos;s Club (ptc) are the currently supported login methods..
        /// </summary>
        internal static string AuthType {
            get {
                return ResourceManager.GetString("AuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurveBalls are a throw add-on and separate from quality, setting this too high may get you flagged..
        /// </summary>
        internal static string CurveThrowChance {
            get {
                return ResourceManager.GetString("CurveThrowChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default Latitude to use, if no LastPos.ini file is found will use these by default.
        /// </summary>
        internal static string DefaultLatitude {
            get {
                return ResourceManager.GetString("DefaultLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default Longitude to use.
        /// </summary>
        internal static string DefaultLongitude {
            get {
                return ResourceManager.GetString("DefaultLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to pause between player actions in milliseconds (1000 ms = 1 second). Integer value..
        /// </summary>
        internal static string DelayBetweenPlayerActions {
            get {
                return ResourceManager.GetString("DelayBetweenPlayerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to pause between Pokemon captures in milliseconds (1000 ms = 1 second). Integer value..
        /// </summary>
        internal static string DelayBetweenPokemonCatch {
            get {
                return ResourceManager.GetString("DelayBetweenPokemonCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device serial number, this is unique per device and should be a 16-digit hexadecimal value.
        /// </summary>
        internal static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device package to use for this bot, use &apos;random&apos; to choose one automatically or &apos;custom&apos; to use your own configs.
        /// </summary>
        internal static string DevicePackageName {
            get {
                return ResourceManager.GetString("DevicePackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimals allowed..
        /// </summary>
        internal static string EvolveAboveIvValue {
            get {
                return ResourceManager.GetString("EvolveAboveIvValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimals allowed..
        /// </summary>
        internal static string EvolveKeptPokemonsAtStorageUsagePercentage {
            get {
                return ResourceManager.GetString("EvolveKeptPokemonsAtStorageUsagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string ExcellentThrowChance {
            get {
                return ResourceManager.GetString("ExcellentThrowChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the IV of a Pokemon is at or above this % it will be favorited and not transfered. Decimals allowed..
        /// </summary>
        internal static string FavoriteMinIvPercentage {
            get {
                return ResourceManager.GetString("FavoriteMinIvPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string ForceExcellentThrowOverCp {
            get {
                return ResourceManager.GetString("ForceExcellentThrowOverCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string ForceExcellentThrowOverIv {
            get {
                return ResourceManager.GetString("ForceExcellentThrowOverIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string ForceGreatThrowOverCp {
            get {
                return ResourceManager.GetString("ForceGreatThrowOverCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string ForceGreatThrowOverIv {
            get {
                return ResourceManager.GetString("ForceGreatThrowOverIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have less stardust than this, upgrades will not be performed..
        /// </summary>
        internal static string GetMinStarDustForLevelUp {
            get {
                return ResourceManager.GetString("GetMinStarDustForLevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Google account password to use for login..
        /// </summary>
        internal static string GooglePassword {
            get {
                return ResourceManager.GetString("GooglePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Google account username to use for login..
        /// </summary>
        internal static string GoogleUsername {
            get {
                return ResourceManager.GetString("GoogleUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full or relative path to the GPX file you want to use for pathing..
        /// </summary>
        internal static string GpxFile {
            get {
                return ResourceManager.GetString("GpxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string GreatThrowChance {
            get {
                return ResourceManager.GetString("GreatThrowChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have run the bot before, this was the last Latitude you were at and a new start will begin here. If no current coords were found on disk, we reset this to the default values..
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the CP or IV% of Pokemon be used as the upgrade priority?.
        /// </summary>
        internal static string LevelUpByCPorIv {
            get {
                return ResourceManager.GetString("LevelUpByCPorIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have run the bot before, this was the last Longitude you were at and a new start will begin here. If no current coords were found on disk, we reset this to the default values..
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the limit on how many berries to use in a single encounter..
        /// </summary>
        internal static string MaxBerriesToUsePerPokemon {
            get {
                return ResourceManager.GetString("MaxBerriesToUsePerPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the limit of balls to throw at a single Pokemon before giving up..
        /// </summary>
        internal static string MaxPokeballsPerPokemon {
            get {
                return ResourceManager.GetString("MaxPokeballsPerPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED. Integer value..
        /// </summary>
        internal static string MaxSpawnLocationOffset {
            get {
                return ResourceManager.GetString("MaxSpawnLocationOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum distance in meters the bot will travel from the Lat/Lon being used. 1000 meters = 1 kilometer, 1600 meters = 1 mile.
        /// </summary>
        internal static string MaxTravelDistanceInMeters {
            get {
                return ResourceManager.GetString("MaxTravelDistanceInMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string NiceThrowChance {
            get {
                return ResourceManager.GetString("NiceThrowChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string NormalThrowChance {
            get {
                return ResourceManager.GetString("NormalThrowChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to choose which Pokemon you do NOT want transferred automatically..
        /// </summary>
        internal static string NoTransferCollection {
            get {
                return ResourceManager.GetString("NoTransferCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pokemon Trainer&apos;s Club account password to use for login..
        /// </summary>
        internal static string PtcPassword {
            get {
                return ResourceManager.GetString("PtcPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pokemon Trainer&apos;s Club account username to use for login..
        /// </summary>
        internal static string PtcUsername {
            get {
                return ResourceManager.GetString("PtcUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When your inventory reaches this pewrcentage of capacity, start a recycle of spare items..
        /// </summary>
        internal static string RecycleInventoryAtUsagePercentage {
            get {
                return ResourceManager.GetString("RecycleInventoryAtUsagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template for how your Pokemon will be renamed. Tokens: {0} is the Pokemon Species, {1} is the IV%.
        /// </summary>
        internal static string RenameTemplate {
            get {
                return ResourceManager.GetString("RenameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string TelegramAPIKey {
            get {
                return ResourceManager.GetString("TelegramAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string TelegramPassword {
            get {
                return ResourceManager.GetString("TelegramPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintains this many Berries during recycle phase..
        /// </summary>
        internal static string TotalAmountOfBerriesToKeep {
            get {
                return ResourceManager.GetString("TotalAmountOfBerriesToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of all types of Pokeballs to keep - balls of lowest quality get recycled first..
        /// </summary>
        internal static string TotalAmountOfPokeballsToKeep {
            get {
                return ResourceManager.GetString("TotalAmountOfPokeballsToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of all types of Potions to keep - potions of lowest quality get recycled first..
        /// </summary>
        internal static string TotalAmountOfPotionsToKeep {
            get {
                return ResourceManager.GetString("TotalAmountOfPotionsToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintains this many Revives during recycle phase..
        /// </summary>
        internal static string TotalAmountOfRevivesToKeep {
            get {
                return ResourceManager.GetString("TotalAmountOfRevivesToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is how many total items you are asking NecroBot to keep during recycle..
        /// </summary>
        internal static string TotalItemsBeingKept {
            get {
                return ResourceManager.GetString("TotalItemsBeingKept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string UpgradePokemonCpMinimum {
            get {
                return ResourceManager.GetString("UpgradePokemonCpMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string UpgradePokemonIvMinimum {
            get {
                return ResourceManager.GetString("UpgradePokemonIvMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND means the Pokemon must meet both IV% and CP requirements - OR means either..
        /// </summary>
        internal static string UpgradePokemonMinimumStatsOperator {
            get {
                return ResourceManager.GetString("UpgradePokemonMinimumStatsOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string UseBerriesBelowCatchProbability {
            get {
                return ResourceManager.GetString("UseBerriesBelowCatchProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use berries on Pokemon at or above this CP level..
        /// </summary>
        internal static string UseBerriesMinCp {
            get {
                return ResourceManager.GetString("UseBerriesMinCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use berries on Pokemon at or above this IV%..
        /// </summary>
        internal static string UseBerriesMinIv {
            get {
                return ResourceManager.GetString("UseBerriesMinIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND means the Pokemon must meet both IV% and CP requirements - OR means either..
        /// </summary>
        internal static string UseBerriesOperator {
            get {
                return ResourceManager.GetString("UseBerriesOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Pokemon above this CP level are found, a Great Ball will be used for throws..
        /// </summary>
        internal static string UseGreatBallAboveCp {
            get {
                return ResourceManager.GetString("UseGreatBallAboveCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Pokemon above this IV% are found, a Great Ball will be used for throws..
        /// </summary>
        internal static string UseGreatBallAboveIv {
            get {
                return ResourceManager.GetString("UseGreatBallAboveIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string UseGreatBallBelowCatchProbability {
            get {
                return ResourceManager.GetString("UseGreatBallBelowCatchProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string UseLuckyEggsMinPokemonAmount {
            get {
                return ResourceManager.GetString("UseLuckyEggsMinPokemonAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Pokemon above this CP level are found, a Master Ball will be used for throws..
        /// </summary>
        internal static string UseMasterBallAboveCp {
            get {
                return ResourceManager.GetString("UseMasterBallAboveCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string UseMasterBallBelowCatchProbability {
            get {
                return ResourceManager.GetString("UseMasterBallBelowCatchProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string UseProxyHost {
            get {
                return ResourceManager.GetString("UseProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for proxy authentication..
        /// </summary>
        internal static string UseProxyPassword {
            get {
                return ResourceManager.GetString("UseProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string UseProxyPort {
            get {
                return ResourceManager.GetString("UseProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username for proxy authentication..
        /// </summary>
        internal static string UseProxyUsername {
            get {
                return ResourceManager.GetString("UseProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Pokemon above this CP level are found, an Ultra Ball will be used for throws..
        /// </summary>
        internal static string UseUltraBallAboveCp {
            get {
                return ResourceManager.GetString("UseUltraBallAboveCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Pokemon above this IV% are found, an Ultra Ball will be used for throws..
        /// </summary>
        internal static string UseUltraBallAboveIv {
            get {
                return ResourceManager.GetString("UseUltraBallAboveIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QED..
        /// </summary>
        internal static string UseUltraBallBelowCatchProbability {
            get {
                return ResourceManager.GetString("UseUltraBallBelowCatchProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How fast your character will move from point to point. For best safety we recommend keeping this at 15 or below. Decimals are allowed..
        /// </summary>
        internal static string WalkingSpeedInKilometerPerHour {
            get {
                return ResourceManager.GetString("WalkingSpeedInKilometerPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port to listen on for the NecroBot websocket service..
        /// </summary>
        internal static string WebSocketPort {
            get {
                return ResourceManager.GetString("WebSocketPort", resourceCulture);
            }
        }
    }
}
