//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Necrui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalSettingsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalSettingsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Necrui.GlobalSettingsRes", typeof(GlobalSettingsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemon to Display at Start.
        /// </summary>
        internal static string AmountOfPokemonToDisplayOnStart {
            get {
                return ResourceManager.GetString("AmountOfPokemonToDisplayOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Of Times To Upgrade Loop.
        /// </summary>
        internal static string AmountOfTimesToUpgradeLoop {
            get {
                return ResourceManager.GetString("AmountOfTimesToUpgradeLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Board Name.
        /// </summary>
        internal static string AndroidBoardName {
            get {
                return ResourceManager.GetString("AndroidBoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Bootloader.
        /// </summary>
        internal static string AndroidBootloader {
            get {
                return ResourceManager.GetString("AndroidBootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Type.
        /// </summary>
        internal static string AuthType {
            get {
                return ResourceManager.GetString("AuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve Throw % Chance.
        /// </summary>
        internal static string CurveThrowChance {
            get {
                return ResourceManager.GetString("CurveThrowChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Latitude.
        /// </summary>
        internal static string DefaultLatitude {
            get {
                return ResourceManager.GetString("DefaultLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Longitude.
        /// </summary>
        internal static string DefaultLongitude {
            get {
                return ResourceManager.GetString("DefaultLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Between Player Actions (ms).
        /// </summary>
        internal static string DelayBetweenPlayerActions {
            get {
                return ResourceManager.GetString("DelayBetweenPlayerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Between Pokemon Catch (ms).
        /// </summary>
        internal static string DelayBetweenPokemonCatch {
            get {
                return ResourceManager.GetString("DelayBetweenPokemonCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Brand.
        /// </summary>
        internal static string DeviceBrand {
            get {
                return ResourceManager.GetString("DeviceBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        internal static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Model.
        /// </summary>
        internal static string DeviceModel {
            get {
                return ResourceManager.GetString("DeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Model Boot.
        /// </summary>
        internal static string DeviceModelBoot {
            get {
                return ResourceManager.GetString("DeviceModelBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Model Identifier.
        /// </summary>
        internal static string DeviceModelIdentifier {
            get {
                return ResourceManager.GetString("DeviceModelIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Package.
        /// </summary>
        internal static string DevicePackageName {
            get {
                return ResourceManager.GetString("DevicePackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolve Above IV%.
        /// </summary>
        internal static string EvolveAboveIvValue {
            get {
                return ResourceManager.GetString("EvolveAboveIvValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolve Pokemon at Storage Usage %.
        /// </summary>
        internal static string EvolveKeptPokemonsAtStorageUsagePercentage {
            get {
                return ResourceManager.GetString("EvolveKeptPokemonsAtStorageUsagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent Throw % Chance.
        /// </summary>
        internal static string ExcellentThrowChance {
            get {
                return ResourceManager.GetString("ExcellentThrowChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Pokemon above IV%.
        /// </summary>
        internal static string FavoriteMinIvPercentage {
            get {
                return ResourceManager.GetString("FavoriteMinIvPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Brand.
        /// </summary>
        internal static string FirmwareBrand {
            get {
                return ResourceManager.GetString("FirmwareBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Fingerprint.
        /// </summary>
        internal static string FirmwareFingerprint {
            get {
                return ResourceManager.GetString("FirmwareFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Tags.
        /// </summary>
        internal static string FirmwareTags {
            get {
                return ResourceManager.GetString("FirmwareTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Type.
        /// </summary>
        internal static string FirmwareType {
            get {
                return ResourceManager.GetString("FirmwareType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Excellent Throw Over CP.
        /// </summary>
        internal static string ForceExcellentThrowOverCp {
            get {
                return ResourceManager.GetString("ForceExcellentThrowOverCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Excellent Throw Over IV%.
        /// </summary>
        internal static string ForceExcellentThrowOverIv {
            get {
                return ResourceManager.GetString("ForceExcellentThrowOverIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Great Throw Over CP.
        /// </summary>
        internal static string ForceGreatThrowOverCp {
            get {
                return ResourceManager.GetString("ForceGreatThrowOverCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Great Throw Over IV%.
        /// </summary>
        internal static string ForceGreatThrowOverIv {
            get {
                return ResourceManager.GetString("ForceGreatThrowOverIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Stardust Reserve for Upgrade.
        /// </summary>
        internal static string GetMinStarDustForLevelUp {
            get {
                return ResourceManager.GetString("GetMinStarDustForLevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Password.
        /// </summary>
        internal static string GooglePassword {
            get {
                return ResourceManager.GetString("GooglePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Username.
        /// </summary>
        internal static string GoogleUsername {
            get {
                return ResourceManager.GetString("GoogleUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPX File.
        /// </summary>
        internal static string GpxFile {
            get {
                return ResourceManager.GetString("GpxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Throw % Chance.
        /// </summary>
        internal static string GreatThrowChance {
            get {
                return ResourceManager.GetString("GreatThrowChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Manufacturer.
        /// </summary>
        internal static string HardwareManufacturer {
            get {
                return ResourceManager.GetString("HardwareManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Model.
        /// </summary>
        internal static string HardwareModel {
            get {
                return ResourceManager.GetString("HardwareModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade by CP or IV%.
        /// </summary>
        internal static string LevelUpByCPorIv {
            get {
                return ResourceManager.GetString("LevelUpByCPorIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Berries Per Pokemon.
        /// </summary>
        internal static string MaxBerriesToUsePerPokemon {
            get {
                return ResourceManager.GetString("MaxBerriesToUsePerPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Balls Per Pokemon.
        /// </summary>
        internal static string MaxPokeballsPerPokemon {
            get {
                return ResourceManager.GetString("MaxPokeballsPerPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Spawn Location Offset.
        /// </summary>
        internal static string MaxSpawnLocationOffset {
            get {
                return ResourceManager.GetString("MaxSpawnLocationOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Travel Distance in Meters.
        /// </summary>
        internal static string MaxTravelDistanceInMeters {
            get {
                return ResourceManager.GetString("MaxTravelDistanceInMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice Throw % Chance.
        /// </summary>
        internal static string NiceThrowChance {
            get {
                return ResourceManager.GetString("NiceThrowChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computed Normal Throw % Chance.
        /// </summary>
        internal static string NormalThrowChance {
            get {
                return ResourceManager.GetString("NormalThrowChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemon to NOT Transfer.
        /// </summary>
        internal static string NoTransferCollection {
            get {
                return ResourceManager.GetString("NoTransferCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTC Password.
        /// </summary>
        internal static string PtcPassword {
            get {
                return ResourceManager.GetString("PtcPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTC Username.
        /// </summary>
        internal static string PtcUsername {
            get {
                return ResourceManager.GetString("PtcUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Inventory at %.
        /// </summary>
        internal static string RecycleInventoryAtUsagePercentage {
            get {
                return ResourceManager.GetString("RecycleInventoryAtUsagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Template.
        /// </summary>
        internal static string RenameTemplate {
            get {
                return ResourceManager.GetString("RenameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram API Key.
        /// </summary>
        internal static string TelegramAPIKey {
            get {
                return ResourceManager.GetString("TelegramAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Password.
        /// </summary>
        internal static string TelegramPassword {
            get {
                return ResourceManager.GetString("TelegramPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Berries to Keep.
        /// </summary>
        internal static string TotalAmountOfBerriesToKeep {
            get {
                return ResourceManager.GetString("TotalAmountOfBerriesToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Balls to Keep.
        /// </summary>
        internal static string TotalAmountOfPokeballsToKeep {
            get {
                return ResourceManager.GetString("TotalAmountOfPokeballsToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Potions to Keep.
        /// </summary>
        internal static string TotalAmountOfPotionsToKeep {
            get {
                return ResourceManager.GetString("TotalAmountOfPotionsToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Revives to Keep.
        /// </summary>
        internal static string TotalAmountOfRevivesToKeep {
            get {
                return ResourceManager.GetString("TotalAmountOfRevivesToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items Being Kept.
        /// </summary>
        internal static string TotalItemsBeingKept {
            get {
                return ResourceManager.GetString("TotalItemsBeingKept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Pokemon Above CP.
        /// </summary>
        internal static string UpgradePokemonCpMinimum {
            get {
                return ResourceManager.GetString("UpgradePokemonCpMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Pokemon Above IV%.
        /// </summary>
        internal static string UpgradePokemonIvMinimum {
            get {
                return ResourceManager.GetString("UpgradePokemonIvMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Stats Operator.
        /// </summary>
        internal static string UpgradePokemonMinimumStatsOperator {
            get {
                return ResourceManager.GetString("UpgradePokemonMinimumStatsOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Berries Below % Probability.
        /// </summary>
        internal static string UseBerriesBelowCatchProbability {
            get {
                return ResourceManager.GetString("UseBerriesBelowCatchProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Berries when Above CP.
        /// </summary>
        internal static string UseBerriesMinCp {
            get {
                return ResourceManager.GetString("UseBerriesMinCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Berries when Above IV%.
        /// </summary>
        internal static string UseBerriesMinIv {
            get {
                return ResourceManager.GetString("UseBerriesMinIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Operator.
        /// </summary>
        internal static string UseBerriesOperator {
            get {
                return ResourceManager.GetString("UseBerriesOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Great Ball Above CP.
        /// </summary>
        internal static string UseGreatBallAboveCp {
            get {
                return ResourceManager.GetString("UseGreatBallAboveCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Great Ball Above IV%.
        /// </summary>
        internal static string UseGreatBallAboveIv {
            get {
                return ResourceManager.GetString("UseGreatBallAboveIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Great Ball Below % Probability.
        /// </summary>
        internal static string UseGreatBallBelowCatchProbability {
            get {
                return ResourceManager.GetString("UseGreatBallBelowCatchProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Lucky Eggs Min Pokemon.
        /// </summary>
        internal static string UseLuckyEggsMinPokemonAmount {
            get {
                return ResourceManager.GetString("UseLuckyEggsMinPokemonAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Master Ball Above CP.
        /// </summary>
        internal static string UseMasterBallAboveCp {
            get {
                return ResourceManager.GetString("UseMasterBallAboveCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Master Ball Below % Probability.
        /// </summary>
        internal static string UseMasterBallBelowCatchProbability {
            get {
                return ResourceManager.GetString("UseMasterBallBelowCatchProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Host.
        /// </summary>
        internal static string UseProxyHost {
            get {
                return ResourceManager.GetString("UseProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Password.
        /// </summary>
        internal static string UseProxyPassword {
            get {
                return ResourceManager.GetString("UseProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Port.
        /// </summary>
        internal static string UseProxyPort {
            get {
                return ResourceManager.GetString("UseProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Username.
        /// </summary>
        internal static string UseProxyUsername {
            get {
                return ResourceManager.GetString("UseProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ultra Ball Above CP.
        /// </summary>
        internal static string UseUltraBallAboveCp {
            get {
                return ResourceManager.GetString("UseUltraBallAboveCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ultra Ball Above IV%.
        /// </summary>
        internal static string UseUltraBallAboveIv {
            get {
                return ResourceManager.GetString("UseUltraBallAboveIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ultra Ball Below % Probability.
        /// </summary>
        internal static string UseUltraBallBelowCatchProbability {
            get {
                return ResourceManager.GetString("UseUltraBallBelowCatchProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking Speed (in KPH).
        /// </summary>
        internal static string WalkingSpeedInKilometerPerHour {
            get {
                return ResourceManager.GetString("WalkingSpeedInKilometerPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSocket Port.
        /// </summary>
        internal static string WebSocketPort {
            get {
                return ResourceManager.GetString("WebSocketPort", resourceCulture);
            }
        }
    }
}
